name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u basilel -p dckr_pat_hbSG54VMPb5yH2f8JnvtOkSRKjg

      - name: Build the Docker image
        run: docker build -t adludio-yolo-challenge .
      - name: Tag the docker file
      - run: docker tag adludio-yolo-challenge basilel/adludio-yolo-challenge:latest
      - name: Push to Dockerhub
        run: docker push basilel/adludio-yolo-challenge:latest
